export const ENlabels = {
    themeDark: 'Dark',
    themeLight: 'Light',
    languaje: 'Languaje',
    userTitle: 'Alexis Eduardo Matamoros',
    userJob: 'Web Developer',
    options: 'Options',
    mainTitle: 'About Me',
    mainMsg: `Hello, I am a Systems Engineer graduated from the Autonomous University of Honduras, my skills are focused on the development of web applications with knowledge of Backend, Frontend technologies and SQL/NOSQL database systems, I also have very good soft skills, such as good intercommunication skills, teamwork, organization, creativity and I also adapt easily to any situation or job.`,
    mainHero: `Welcome to my portfolio`,
    cvButton: 'Download CV',
    frase: `"No matter how high is a mountain, there is always a way to the top."`,
    homeTitle: 'Home',
    blogTitle: 'Blog',
    tecnologiesTitle: 'Tecs',
    contactTitle: 'Contact',
    proyectsTitle: 'Proyects',
    techsTitle: 'Techs',
    experience: 'Experience',
    footerText: 'Generated with REACT, TailwindCSS, VSCode and a lot of love.',
    contactFullName: 'Full Name',
    contactEmail: 'Your email',
    contactSubject: 'Tell me, how can i help you?',
    tecsResume: 'Recently used technologies:',
    tecsPrevius: 'These are some of the technologies I worked with previously.',
    requiredField: 'Required Field',
};
